[build]
  command = "npm install && npm start"
  publish = "public"  # Ganti dengan direktori hasil build Anda

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[build.environment]
  NODE_VERSION = "14"  # Sesuaikan dengan versi Node.js yang Anda gunakan
